version: '3'
services:
  spring-boot-reactive-service:
    container_name: spring-boot-reactive-service
    image: personal/spring-boot-reactive-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_HOST=${HOST_IP} #Public IPv4 address of aws -instance
      - SPRING_DATASOURCE_PORT=5432